# main menu navigation
menu:
  home: /
  archives: /archives
  about: /about
  rss: /atom.xml

# Miscelaneous
favicon: /favicon.ico

show_post_category: true
show_post_tags: true

active_nav: false # show active status on nav menu

sidebar: true # whether to show the sidebar
widgets:
  # - category
  # - tag
  # - tagcloud
  # - archive
  - recent_posts
  - links
links:
  - title: "GitHub"
    url: https://github.com/zhngymn36181654
    intro: "GitHub"

newsroom:
  enable: true
  hero_count: 2
  default_cover:
  

# disqus_shortname: wayou
# duoshuo_shortname: wayouliu
#site statistic
google_analytics:  
# baidu_analytics: 392796d51567e848aebf813b65cb8656
baidu_analytics: 


